from lib.constants.direction import DIRECTION

# 盤面の大きさ
BOARD_WIDTH = 10 # WIDTHは固定。動かすことはできない
BOARD_HEIGHT = 40
DISPLAYED_BOARD_HEIGHT = 20 # 実際に「表示」されている盤面の高さ
FOLLOWING_MINOS_COUNT = 5

# ミノの出現時の向き・位置
FIRST_MINO_POS = (4, BOARD_HEIGHT - DISPLAYED_BOARD_HEIGHT)
FIRST_MINO_DIRECTION = DIRECTION.N