# 攻撃力
SCORE_SINGLE = 0
SCORE_DOUBLE = 1
SCORE_TRIPLE = 2
SCORE_TETRIS = 4
SCORE_T_SPIN_MINI = 0
SCORE_T_SPIN_SINGLE = 2
SCORE_T_SPIN_DOUBLE = 4
SCORE_T_SPIN_TRIPLE = 6
SCORE_BACK_TO_BACK  = 1
SCORE_PERFECT_CLEAR = 10
SCORE_REN = [0,0,1,1,2,2,3,3,4,4,4,5,5,5,5]